---
version: "3"
includes:
  build:
    taskfile: ./taskfiles/Taskfile_build.yml
  storybook:chainpresence:
    taskfile: ./taskfiles/Taskfile_storybook.yml
    aliases: [sb:chainpresence]
    vars:
      WORKSPACE: "chainpresence"
  

tasks:
  build:
    desc: "build everything"
    cmds:
      - task: build:gav0

  build:gav0:
    desc: "build everything for gav0"
    cmds:
      - task: build:package:chainpresence
      - task: build:app:gav0
