version: '3'

dotenv:
  - ".env"
  # - ".env.secret"
  # - .env.{{.TASK_GROUP}}.{{.ENV_NAME}}

includes:
  chaintrap:
    taskfile: ./taskfiles/Taskfile_chaintrap.yml

tasks:
  abi:
    desc: "output the abi"
    cmds:
      - |
        task -d $CONTRACTS_CHAINTRAP_DIR abi