<script lang="ts">

// This component holds the elements that control what is done with the content
// generated by the Fabricator. Typically, saving it somewhere, minting an nft,
// deploying some contracts etc. The implemntation components are always game specific

// --- lib deps
// --- framework
// import { onMount , setContext, getContext, onDestroy } from 'svelte'
// --- external components
// --- components
// --- app lib
// --- app stores
// --- constants
// --- data imports
// --- component properties
// --- component state properties
// --- svelte bound variables
// let instance = undefined
// --- svelte lifecycle callbacks
// test support hook
// onMount(async () => {})
// --- on dom event callbacks
// --- contract state callbacks
// --- component helpers
</script>
<div class="flex flex-col full-height">
  <div class="flex-grow-0 flex-shrink-0 basis-1/2 card  variant-soft-surface md:mb-2">
    <slot name="top"></slot>
  </div>
  <div class="flex-grow-0 flex-shrink-0 basis-1/4 card  variant-soft-surface">
    <slot name="bottom"></slot>
  </div>
</div>
<style>
  /* Ensure the container takes the full height of the viewport */
  .full-height {
    height: 100vh;
  }
</style>