name: 'Storybook Tests'
on: push
env:
  PNPM_WORKSPACE: 'chainpresence'
  WORKSPACE_PATH: 'packages/chainpresence'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9.5

      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: pnpm -F ${PNPM_WORKSPACE} install

      - name: Install Playwright
        run: pnpm exec playwright install --with-deps
        working-directory: ${{ env.WORKSPACE_PATH }}

      - name: Build Storybook
        run: pnpm build-storybook --quiet
      - name: Serve Storybook and run tests
        run: |
          pnpm dlx concurrently -k -s first -n "SB,TEST" -c "magenta,blue" \
            "pnpm http-server storybook-static --port 6006 --silent" \
            "pnpm wait-on tcp:127.0.0.1:6006 && pnpm test-storybook"
